import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import React from "react";
import {Provider} from "react-redux";
import store from "@/Redux/Store";
import {AuthProvider} from "@/Context/AuthContext";
import {Providers} from "@/Redux/Provider";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <Providers>
            <AuthProvider>
                <body
                    className={inter.className + " relative bg-violet-950 flex overflow-clip text-white flex-col min-h-screen max-w-screen "}>{children}</body>
            </AuthProvider>
        </Providers>
        </html>
    );
}
